export const COMMUNES_ABIDJAN = [
  'Cocody', 'Plateau', 'Marcory', 'Treichville', 'Adjamé', 'Yopougon',
  'Abobo', 'Koumassi', 'Port-Bouet', 'Bingerville', 'Attécoubé', 'Songon', 'Anyama',
] as const

export type CommuneAbidjan = typeof COMMUNES_ABIDJAN[number]

export const COMMUNES_HORS_ABIDJAN = [
  'Abengourou',
  'Aboisso',
  'Adiaké',
  'Adzopé',
  'Agboville',
  'Agnibilékrou',
  'Akoupé',
  'Alepe',
  'Arrah',
  'Assinie',
  'Azaguié',
  'Bassam (Grand-Bassam)',
  'Béoumi',
  'Biankouma',
  'Bocanda',
  'Bondoukou',
  'Bongouanou',
  'Bonon',
  'Bonoua',
  'Bouaflé',
  'Bouaké',
  'Bouna',
  'Boundiali',
  'Dabakala',
  'Dabou',
  'Daloa',
  'Danané',
  'Daoukro',
  'Dimbokro',
  'Divo',
  'Duékoué',
  'Ferkessédougou',
  'Fresco',
  'Gagnoa',
  'Grand-Béréby',
  'Grand-Lahou',
  'Guiglo',
  'Issia',
  'Jacqueville',
  'Katiola',
  'Kong',
  'Korhogo',
  'Lakota',
  "M'Bahiakro",
  "M'Batto",
  'Man',
  'Mankono',
  'Méagui',
  'Odienné',
  'Oumé',
  'Sakassou',
  'San-Pédro',
  'Sassandra',
  'Séguéla',
  'Sikensi',
  'Sinfra',
  'Soubré',
  'Taabo',
  'Tabou',
  'Tanda',
  'Tengréla',
  'Tiapoum',
  'Tiassalé',
  'Tiébissou',
  'Touba',
  'Toumodi',
  'Vavoua',
  'Yamoussoukro',
  'Zuénoula',
] as const

export const COMMUNES_CI = [
  ...COMMUNES_ABIDJAN,
  ...COMMUNES_HORS_ABIDJAN,
] as const

export const QUARTIERS_PREMIUM = [
  'Riviera Faya', 'Riviera Golf', 'Palmeraie', 'Cocody II Plateaux',
  'Angré', 'Deux Plateaux Vallon', 'Riviera 3', 'Riviera Bonoumin',
] as const

export const ROLES_UTILISATEUR = ['locataire', 'proprietaire', 'agence', 'admin'] as const
export type RoleUtilisateur = typeof ROLES_UTILISATEUR[number]

